root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/api ./cmd/api"
  bin = "tmp/api"
  full_bin = ""
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "logs", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]

[log]
  time = true

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "magenta"

[misc]
  clean_on_exit = true
