services:
  - type: web
    runtime: go
    name: go-api
    repo: https://github.com/zabaletac3/template_golang # Cambiar
    branch: main
    buildCommand: go build -o server ./cmd/api
    startCommand: ./server
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGO_URI
        sync: false # Configurar en Dashboard
      - key: MONGO_DATABASE
        sync: false # Configurar en Dashboard
      - key: JWT_SECRET
        sync: false # Configurar en Dashboard
      - key: JWT_EXPIRATION_MINS
        value: "15"
      - key: JWT_REFRESH_EXPIRATION_DAYS
        value: "7"
    healthCheckPath: /health
    autoDeploy: true
