services:
  - type: web
    runtime: go
    name: go-api
    repo: https://github.com/tu-usuario/tu-repo # Cambiar
    branch: main
    buildCommand: go build -o server ./cmd/api
    startCommand: ./server
    envVars:
      - key: APP_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: MONGO_URI
        sync: false # Se configura manualmente en Render Dashboard
      - key: MONGO_DATABASE
        sync: false
    healthCheckPath: /health
    autoDeploy: true
